name: fire_pilot
description: Elite Firebase setup orchestrator for Flutter. Automates Node.js install, multi-account login, project creation, and SHA registration.
version: 1.0.5
homepage: https://github.com/Gourav-sharma/fire_pilot
repository: https://github.com/Gourav-sharma/fire_pilot
issue_tracker: https://github.com/Gourav-sharma/fire_pilot/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  interact: ^2.2.0

executables:
  fire_pilot: